CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USER_NAME NVARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD NVARCHAR2(50) NOT NULL,
    COUNTRY NVARCHAR2(50),
    USER_TYPE NVARCHAR2(50) DEFAULT 'USER' NOT NULL,
    CHECK (USER_TYPE = 'ADMIN' OR USER_TYPE = 'USER')
);