CREATE TABLE ORDERS(
    ID NUMBER PRIMARY KEY,
    USER_ORDERED NUMBER NOT NULL,
    CONSTRAINT USER_FK FOREIGN KEY(USER_ORDERED) REFERENCES USERS(ID),
    ROOM NUMBER NOT NULL,
    CONSTRAINT ROOM_FK FOREIGN KEY(ROOM) REFERENCES ROOM(ID),
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID NUMBER(*, 2)
);