CREATE TABLE ROOM (
    ID NUMBER PRIMARY KEY,
    NUMBER_OF_GUESTS NUMBER DEFAULT 1 NOT NULL,
    PRICE NUMBER(*, 2),
    BREAKFAST_INCLUDED NUMBER(1) DEFAULT 0,
    CHECK (BREAKFAST_INCLUDED BETWEEN 0 AND 1),
    PETS_ALLOWED NUMBER(1) DEFAULT 0,
    CHECK (PETS_ALLOWED BETWEEN 0 AND 1),
    DATE_AVAILABLE_FROM TIMESTAMP NOT NULL,
    HOTEL NUMBER NOT NULL,
    CONSTRAINT HOTEL_FK FOREIGN KEY(HOTEL) REFERENCES HOTEL(ID)
);